//
//  Database.swift
//  Portfolio
//
//  Created by Cindy Bajoni on 10/06/2023.
//

import Foundation

var tabBarItem : [TabItemData] = [TabItemData(imageTab: "helloblackmemoji", selectedImage: "hellomemoji", titleTab: "Bienvenue"),
                TabItemData(imageTab: "blackmemoji", selectedImage: "memojipng", titleTab: "Portfolio"),
                TabItemData(imageTab: "studyblackmemoji", selectedImage: "studymemoji", titleTab: "Expériences"),
                TabItemData(imageTab: "loveblackmemoji", selectedImage: "lovememoji", titleTab: "À propos"),
                TabItemData(imageTab: "callblackmemoji", selectedImage: "callmemoji", titleTab: "Contacts")]

var moi = Contacts(prenom: "Cindy", nom: "Bajoni", age: 31, lieu: "Occitanie  PACA", telephone: "07.86.30.58.99", email: "cindie-baj@live.fr", linkedin: "https://www.linkedin.com/in/cindy-bajoni/", github: "https://github.com/Cindoushka", photographie: "https://cindiebphotography.wixsite.com/book", photo: "cindie", posteRecherche: "Développeuse iOS")

var formations : [ExperiencesPro] = [ExperiencesPro(entreprise: "Studi", ville: "Autonomie", intitule: "Bachelor Développeur Mobile iOS", description: "Préparation au diplôme Concepteur Développeur d'Applications mobile avec spécialisation iOS. Apprentissage de la partie back-end avec PHP et SQL. Apprentissage de Java et approfondissement de Swift/SwiftUI pour le développement d'applications mobile.", softSkills: [.autonomie, .creativite, .gestion, .organisation], hardSkills: [.figma, .java, .swift, .swiftui, .php,.sql], diplome: "Bachelor", image: "studi", periode: "2023"),
                                     ExperiencesPro(entreprise: "Simplon", ville: "Lille", intitule: "Développeur intégrateur d'applications", description: "Apprentissage des langages HTML5, CSS3 et JavaScript. Réalisation de plusieurs projets en groupe, allant d'un blog simple à un site beaucoup plus élaboré.", softSkills: [.autonomie, .communication, .creativite, .gestion, .organisation, .team], hardSkills: [.html, .css, .sass, .js, .figma, .github], diplome: "", image: "simplon", periode: "2022"),
                                     ExperiencesPro(entreprise: "Simplon", ville: "Distanciel", intitule: "Apple Foundation Program - Extended", description: "Approfondissement des compétences apprises lors de l'Apple Foundation Program, j'ai notamment appris à intégrer une map à mon application et à l'utiliser; ou encore à utiliser des filtres etc...", softSkills: [.autonomie, .communication, .creativite, .gestion ,.organisation, .team], hardSkills: [.figma, .swift, .swiftui, .github], diplome: "Certification", image: "simplon", periode: "2022"),
                                     ExperiencesPro(entreprise: "Simplon", ville: "Lille", intitule: "Apple Foundation Program", description: "Conception d'un prototype d'application iOS en travail de groupe. On a tout d'abord choisit un thème, puis nous en avons dégagé une problèmatique à laquelle devait répondre notre projet. Nous avons ensuite mis en place une maquette. Après avoir appris les langages Swift et SwiftUI, appris à manipuler xCode, nous avons réaliser le prototype. Retrouvez le prototype dans la section réalisations. J'ai tout remanié pour que cela soit fait par moi-même.", softSkills: [.autonomie, .communication, .creativite, .gestion ,.organisation, .team], hardSkills: [.swift, .swiftui], diplome: "Certification", image: "simplon", periode: "2022"),
                                     ExperiencesPro(entreprise: "Lycée Gaston Berger", ville: "Lille", intitule: "BTS Négociations Relations Client", description: "Apprentissage des techniques de ventes et de négociations. Apprentissage de méthodes pour mettre en place de bonnes relations clients.", softSkills: [.gestion, .organisation, .nego, .langues], hardSkills: [], diplome: "BTS", image: "gaston", periode: "2014-2016"),
                                     ExperiencesPro(entreprise: "Lycée Gaston Berger", ville: "Lille", intitule: "TOEIC", description: "J'ai obtenu le TOEIC avec un score de 880.", softSkills: [.langues], hardSkills: [.anglais], diplome: "880", image: "gaston", periode: "2016"),
                                     ExperiencesPro(entreprise: "Lycée Albert Châtelet", ville: "Douai", intitule: "Baccalauréat S", description: "Bac S Spé maths, énormément de mathématiques durant les deux dernières années de baccalauréat.", softSkills: [], hardSkills: [.anglais, .italien, .espagnol], diplome: "Baccalauréat Scientifique spécialité Maths", image: "chatelet", periode: "2010")
]

var emplois : [ExperiencesPro] = [ExperiencesPro(entreprise: "Assur'Travel", ville: "Villeneuve d'Ascq", intitule: "Développeuse front-end", description: "Réalisation de tâches front-end en contexte Agile. Mise en place et utilisation de la persistance de données à travers le site. Création de PDF en format HTML/CSS à générer grâce à Puppeeter", softSkills: [.communication, .organisation, .team], hardSkills: [.html, .css, .github, .svelte], diplome: "Stage", image: "assur", periode: "2022-2023"),
                                  ExperiencesPro(entreprise: "Caisse d'Épargne", ville: "Roubaix", intitule: "Conseillère de clientèle", description: "Accueil client, gestion du porte-feuille client, vente de produits d'assurances et prévoyances, de crédits à la consommation et immobilier, gestion et vente d'assurances vies.", softSkills: [.communication, .gestion, .nego, .organisation, .autonomie, .team], hardSkills: [], diplome: "CDI", image: "cehdf", periode: "2020-2021"),
                                  ExperiencesPro(entreprise: "Maaf", ville: "La Madeleine", intitule: "Conseillère commerciale", description: "Réception d'appels entrants de clients et prospects, gestion et vente de produits d'assurance et de prévoyance, proposition d'assurances vies et prise de rendez-vous.", softSkills: [.autonomie, .communication, .langues, .nego, .team], hardSkills: [.anglais], diplome: "CDI", image: "maaf", periode: "2019-2020"),
                                  ExperiencesPro(entreprise: "CACF", ville: "Roubaix", intitule: "Conseillère Clientèle", description: "Appels entrants et sortant dans la gestion et vente de crédits renouvelables et crédit amortissables à la consommation", softSkills: [.autonomie, .communication, .langues, .nego, .team], hardSkills: [.anglais], diplome: "Intérimaire", image: "cacf", periode: "2018-2019"),
                                  ExperiencesPro(entreprise: "Caisse d'Épargne", ville: "Douai", intitule: "Conseillère Clientèle Multimedia", description: "Appels entrants et sortants des clients des différentes agences des Hauts-de-France, rebonds commerciaux sur les produits bancaires et d'assurances.", softSkills: [.autonomie, .communication, .nego, .team], hardSkills: [], diplome: "CDD", image: "cehdf", periode: "2017-2018"),
                                  ExperiencesPro(entreprise: "Orange", ville: "Arras", intitule: "Conseillère commerciale", description: "Accueil des clients, ventes de forfaits mobile et internet, vente de téléphones mobiles et fixes.", softSkills: [.autonomie, .communication, .langues, .nego, .team], hardSkills: [.anglais], diplome: "Intérimaire", image: "orange", periode: "2016-2017"),
                                  ExperiencesPro(entreprise: "Orange", ville: "Lille", intitule: "Conseillère technique", description: "Accueil des clients, prise en charge des demandes techniques (paramètrages, réparation et maintenance de téléphones mobiles, ordinateurs portables et box internet). Rebonds commerciaux.", softSkills: [.autonomie, .communication, .langues, .nego, .team], hardSkills: [.anglais], diplome: "Alternance", image: "orange", periode: "2014-2016"),
                                  ExperiencesPro(entreprise: "H&M", ville: "Lille", intitule: "Vendeuse", description: "Mise en rayon, étiquetage et rangement des vêtements, encaissement.", softSkills: [.autonomie, .communication, .team], hardSkills: [], diplome: "CDD", image: "hm", periode: "2014"),
                                  ExperiencesPro(entreprise: "DMS Préventions", ville: "Lille", intitule: "Vendeuse à Domicile Indépendante", description: "Vente à domicile au porte-à-porte d'alarmes.", softSkills: [.autonomie, .communication, .nego], hardSkills: [], diplome: "VDI", image: "alarm", periode: "2014"),
                                  ExperiencesPro(entreprise: "McDonald's", ville: "Douai", intitule: "Barista", description: "Barista au McCafé, préparation de boissons type macchiato, cappuccino, mais aussi Smoothies, cuisson de viennoiseries, mise en rayon, nettoyage et respect des règles d'hygiène.", softSkills: [.autonomie, .communication, .creativite, .team], hardSkills: [], diplome: "CDI", image: "mcdo", periode: "2014"),
                                  ExperiencesPro(entreprise: "Lycée d'Excellence", ville: "Douai", intitule: "Assisante d'Éducation", description: "Accompagnement des élèves du Lycée d'Excellence Edgar Morin de 12 à 18 ans au quotidien, du petit déjeuner au coucher. Surveillance des heures de permanence et des récréations. Aide aux devoirs. Organisation et encadrement d'activités telles que des sorties au cinéma, des soirées à thèmes et d'un club cinéma les mercredis soirs.", softSkills: [.autonomie, .communication, .creativite, .langues, .organisation, .team], hardSkills: [.anglais], diplome: "Service Civique", image: "lycee", periode: "2012-2013")
]

